import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {chromium} from 'playwright';
const executablePath=execFileSync('which',['chromium'],{encoding:'utf8'}).trim();
const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox']});
const errors=[];const failures=[];const report={};
async function wire(page){page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('favicon'))errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));page.on('requestfailed',request=>{if(!request.url().includes('sw.js'))failures.push(`${request.url()} ${request.failure()?.errorText}`);});}
const desktop=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});await wire(desktop);
await desktop.goto('http://127.0.0.1:4174/app.html',{waitUntil:'networkidle'});
assert.equal(await desktop.locator('[data-step="1"]').isVisible(),true);
await desktop.locator('[data-sample="woocommerce"]').click();
await desktop.locator('[data-step="2"]').waitFor({state:'visible'});
assert.match(await desktop.locator('#sourceReadout').innerText(),/WooCommerce/);
assert.equal(await desktop.locator('#fileName').innerText(),'woocommerce.csv');
await desktop.locator('#convertButton').click();
assert.equal(await desktop.locator('[data-step="3"]').isVisible(),true);
assert.equal(await desktop.locator('#metricProducts').innerText(),'1');
assert.equal(await desktop.locator('#metricVariants').innerText(),'2');
assert.equal(await desktop.locator('#metricCritical').innerText(),'0');
assert.match(await desktop.locator('#resultState').innerText(),/PREFLIGHT CLEAR/);
await desktop.locator('[data-go="4"]').click();
assert.equal(await desktop.locator('[data-step="4"]').isVisible(),true);
const downloadPromise=desktop.waitForEvent('download');await desktop.locator('#downloadShopify').click();const download=await downloadPromise;const path=await download.path();const exported=readFileSync(path,'utf8');
assert.equal(download.suggestedFilename(),'woocommerce-shopify-ready.csv');
assert.match(exported,/Variant SKU/);assert.match(exported,/LINEN-S/);assert.match(exported,/34\.99/);
await desktop.locator('#newRun').click();await desktop.locator('[data-sample="problem-file"]').click();await desktop.locator('#convertButton').click();
assert.ok(Number(await desktop.locator('#metricCritical').innerText())>=3);
await desktop.locator('[data-filter="critical"]').click();
assert.ok(await desktop.locator('#previewBody tr').count()>=1);
report.desktopOverflow=await desktop.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
await desktop.screenshot({path:'app-desktop.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844}});await wire(mobile);await mobile.goto('http://127.0.0.1:4174/app.html',{waitUntil:'networkidle'});await mobile.locator('[data-sample="squarespace"]').click();await mobile.locator('[data-step="2"]').waitFor({state:'visible'});await mobile.locator('#convertButton').click();
assert.equal(await mobile.locator('#metricProducts').innerText(),'1');assert.equal(await mobile.locator('#metricVariants').innerText(),'2');
report.mobileOverflow=await mobile.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
await mobile.screenshot({path:'app-mobile.png',fullPage:true});
report.errors=errors;report.failures=failures;assert.equal(report.desktopOverflow,0);assert.equal(report.mobileOverflow,0);assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);
await browser.close();console.log(JSON.stringify(report,null,2));
